import type { Metadata } from "next";
import * as fonts from "@/lib/fonts";
import "./globals.css";
import ReactLenis from "lenis/react";
import { PageLoadContextProvider } from "@/context/loading-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fonts.AkiraBold.variable} ${fonts.AkiraOutline.variable} ${fonts.OTJubileeDiamond.variable} min-h-svh text-black/75 antialiased`}
      >
        <ReactLenis root>{children}</ReactLenis>
      </body>
    </html>
  );
}
